# Generated by Django 3.1.2 on 2021-01-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('albumtitle', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('hero', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.CharField(max_length=250)),
                ('albumname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.album')),
            ],
        ),
    ]
