# Generated by Django 3.1.2 on 2021-04-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='Album_logo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songname',
            new_name='Picture',
        ),
        migrations.RemoveField(
            model_name='album',
            name='hero',
        ),
    ]
