# Generated by Django 3.1.2 on 2021-04-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210421_0046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='song',
            new_name='Photo',
        ),
    ]
