# Generated by Django 3.1.2 on 2021-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210421_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Album_logo',
            field=models.FileField(max_length=250, upload_to=''),
        ),
    ]
