# Generated by Django 3.1.2 on 2021-04-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210421_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Description',
            new_name='Owner',
        ),
    ]
