# Generated by Django 3.1.2 on 2021-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210424_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Album_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
