# Generated by Django 3.1.2 on 2021-07-16 13:34

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210716_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Album_logo',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.upload_location),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Picture',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.upload_loc),
        ),
    ]
